// Command openapiembed packages an OpenAPI document into generated Go source.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

func main() {
	inputPath := flag.String("input", "", "path to the OpenAPI document")
	outputPath := flag.String("output", "", "path to the generated Go file")
	flag.Parse()

	if *inputPath == "" || *outputPath == "" {
		fail("both -input and -output are required")
	}

	spec, err := os.ReadFile(*inputPath)
	if err != nil {
		fail("read OpenAPI document: %v", err)
	}

	var source bytes.Buffer
	source.WriteString(`// Code generated by internal/tools/openapiembed; DO NOT EDIT.

package openapi

var openAPI3YAML = []byte(
`)
	lines := bytes.SplitAfter(spec, []byte("\n"))
	if len(lines) > 1 && len(lines[len(lines)-1]) == 0 {
		lines = lines[:len(lines)-1]
	}
	for index, line := range lines {
		_, _ = fmt.Fprintf(&source, "\t%q", line)
		if index < len(lines)-1 {
			source.WriteString(" +")
		} else {
			source.WriteByte(',')
		}
		source.WriteByte('\n')
	}
	source.WriteString(")\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		fail("format generated Go source: %v", err)
	}

	if err := os.MkdirAll(filepath.Dir(*outputPath), 0o755); err != nil {
		fail("create output directory: %v", err)
	}

	temporaryPath := *outputPath + ".tmp"
	if err := os.WriteFile(temporaryPath, formatted, 0o644); err != nil {
		fail("write temporary output: %v", err)
	}
	if err := os.Rename(temporaryPath, *outputPath); err != nil {
		_ = os.Remove(temporaryPath)
		fail("replace generated output: %v", err)
	}
}

func fail(message string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, "openapiembed: "+message+"\n", args...)
	os.Exit(1)
}
