package bootstrap

import (
	"github.com/endge-lab/service-backend/internal/usecase/actions"
	"github.com/endge-lab/service-backend/internal/usecase/auth_profiles"
	"github.com/endge-lab/service-backend/internal/usecase/backups"
	"github.com/endge-lab/service-backend/internal/usecase/commits"
	"github.com/endge-lab/service-backend/internal/usecase/components"
	"github.com/endge-lab/service-backend/internal/usecase/compositions"
	"github.com/endge-lab/service-backend/internal/usecase/computations"
	"github.com/endge-lab/service-backend/internal/usecase/converters"
	"github.com/endge-lab/service-backend/internal/usecase/data_views"
	"github.com/endge-lab/service-backend/internal/usecase/documents"
	"github.com/endge-lab/service-backend/internal/usecase/environments"
	"github.com/endge-lab/service-backend/internal/usecase/filters"
	"github.com/endge-lab/service-backend/internal/usecase/folders"
	"github.com/endge-lab/service-backend/internal/usecase/history"
	"github.com/endge-lab/service-backend/internal/usecase/i18n_bundles"
	"github.com/endge-lab/service-backend/internal/usecase/integrations"
	"github.com/endge-lab/service-backend/internal/usecase/mocks"
	"github.com/endge-lab/service-backend/internal/usecase/navigations"
	"github.com/endge-lab/service-backend/internal/usecase/portable"
	"github.com/endge-lab/service-backend/internal/usecase/projects"
	"github.com/endge-lab/service-backend/internal/usecase/queries"
	"github.com/endge-lab/service-backend/internal/usecase/releases"
	"github.com/endge-lab/service-backend/internal/usecase/revisions"
	"github.com/endge-lab/service-backend/internal/usecase/session"
	"github.com/endge-lab/service-backend/internal/usecase/stores"
	"github.com/endge-lab/service-backend/internal/usecase/streams"
	"github.com/endge-lab/service-backend/internal/usecase/styles"
	"github.com/endge-lab/service-backend/internal/usecase/tenants"
	"github.com/endge-lab/service-backend/internal/usecase/types"
	"github.com/endge-lab/service-backend/internal/usecase/updates"
	"github.com/endge-lab/service-backend/internal/usecase/vocabs"
	"github.com/endge-lab/service-backend/internal/usecase/workspace_state"
	"github.com/endge-lab/service-backend/internal/usecase/workspaces"
	"go.uber.org/fx"
)

func UseCaseModules() fx.Option {
	return fx.Options(fx.Provide(
		workspace_state.NewCoordinator,
		history.NewRecorder,
		documents.NewLifecycle,
		workspaces.NewUseCase,
		integrations.NewUseCase,
		session.NewUseCase,
		projects.NewUseCase,
		tenants.NewUseCase,
		environments.NewUseCase,
		folders.NewUseCase,
		types.NewUseCase,
		queries.NewUseCase,
		data_views.NewUseCase,
		compositions.NewUseCase,
		stores.NewUseCase,
		streams.NewUseCase,
		updates.NewUseCase,
		mocks.NewUseCase,
		components.NewUseCase,
		actions.NewUseCase,
		filters.NewUseCase,
		converters.NewUseCase,
		computations.NewUseCase,
		vocabs.NewUseCase,
		i18n_bundles.NewUseCase,
		auth_profiles.NewUseCase,
		navigations.NewUseCase,
		styles.NewUseCase,
		revisions.NewUseCase,
		commits.NewUseCase,
		portable.NewUseCase,
		releases.NewUseCase,
		backups.NewUseCase,
	))
}
