// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: component.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countComponents = `-- name: CountComponents :one
SELECT COUNT(*)
FROM components
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (
    $2::uuid IS NULL
      OR folder_id = $2
    )
  AND (
    $3::text IS NULL
      OR component_type = $3
    )
`

type CountComponentsParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	FolderID      pgtype.UUID `json:"folder_id"`
	ComponentType pgtype.Text `json:"component_type"`
}

func (q *Queries) CountComponents(ctx context.Context, arg CountComponentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComponents, arg.ProjectID, arg.FolderID, arg.ComponentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (
    project_id,
    folder_id,
    identity,
    display_name,
    description,
    component_type,
    source,
    source_format,
    props_schema,
    bindings,
    meta,
    active
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9,
           $10,
           $11,
           $12
       )
    RETURNING id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
`

type CreateComponentParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	FolderID      uuid.UUID   `json:"folder_id"`
	Identity      string      `json:"identity"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	ComponentType string      `json:"component_type"`
	Source        string      `json:"source"`
	SourceFormat  string      `json:"source_format"`
	PropsSchema   []byte      `json:"props_schema"`
	Bindings      []byte      `json:"bindings"`
	Meta          []byte      `json:"meta"`
	Active        bool        `json:"active"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.ProjectID,
		arg.FolderID,
		arg.Identity,
		arg.DisplayName,
		arg.Description,
		arg.ComponentType,
		arg.Source,
		arg.SourceFormat,
		arg.PropsSchema,
		arg.Bindings,
		arg.Meta,
		arg.Active,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsComponentByIdentity = `-- name: ExistsComponentByIdentity :one
SELECT EXISTS (
    SELECT 1
    FROM components
    WHERE project_id = $1
      AND identity = $2
)
`

type ExistsComponentByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) ExistsComponentByIdentity(ctx context.Context, arg ExistsComponentByIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsComponentByIdentity, arg.ProjectID, arg.Identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getComponentByID = `-- name: GetComponentByID :one
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetComponentByID(ctx context.Context, id uuid.UUID) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByID, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComponentByIdentity = `-- name: GetComponentByIdentity :one
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components
WHERE project_id = $1
  AND identity = $2
  AND deleted_at IS NULL
`

type GetComponentByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetComponentByIdentity(ctx context.Context, arg GetComponentByIdentityParams) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByIdentity, arg.ProjectID, arg.Identity)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComponentByIdentityIncludingDeleted = `-- name: GetComponentByIdentityIncludingDeleted :one
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components
WHERE project_id = $1
  AND identity = $2
`

type GetComponentByIdentityIncludingDeletedParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetComponentByIdentityIncludingDeleted(ctx context.Context, arg GetComponentByIdentityIncludingDeletedParams) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByIdentityIncludingDeleted, arg.ProjectID, arg.Identity)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteComponent = `-- name: HardDeleteComponent :execrows
DELETE FROM components
WHERE id = $1
`

func (q *Queries) HardDeleteComponent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteComponent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listComponents = `-- name: ListComponents :many
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (
    $2::uuid IS NULL
      OR folder_id = $2
    )
  AND (
    $3::text IS NULL
      OR component_type = $3
    )
ORDER BY created_at DESC
`

type ListComponentsParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	FolderID      pgtype.UUID `json:"folder_id"`
	ComponentType pgtype.Text `json:"component_type"`
}

func (q *Queries) ListComponents(ctx context.Context, arg ListComponentsParams) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponents, arg.ProjectID, arg.FolderID, arg.ComponentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Component
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Identity,
			&i.DisplayName,
			&i.Description,
			&i.ComponentType,
			&i.Source,
			&i.SourceFormat,
			&i.PropsSchema,
			&i.Bindings,
			&i.Meta,
			&i.Active,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreComponent = `-- name: RestoreComponent :execrows
UPDATE components
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreComponent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreComponent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteComponent = `-- name: SoftDeleteComponent :execrows
UPDATE components
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComponent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComponent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components
SET
    folder_id = $1,
    display_name = $2,
    description = $3,
    component_type = $4,
    source = $5,
    source_format = $6,
    props_schema = $7,
    bindings = $8,
    meta = $9,
    active = $10,
    updated_at = NOW()
WHERE id = $11
  AND deleted_at IS NULL
    RETURNING id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
`

type UpdateComponentParams struct {
	FolderID      uuid.UUID   `json:"folder_id"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	ComponentType string      `json:"component_type"`
	Source        string      `json:"source"`
	SourceFormat  string      `json:"source_format"`
	PropsSchema   []byte      `json:"props_schema"`
	Bindings      []byte      `json:"bindings"`
	Meta          []byte      `json:"meta"`
	Active        bool        `json:"active"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.FolderID,
		arg.DisplayName,
		arg.Description,
		arg.ComponentType,
		arg.Source,
		arg.SourceFormat,
		arg.PropsSchema,
		arg.Bindings,
		arg.Meta,
		arg.Active,
		arg.ID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
