// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: component_legacy.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countComponentsLegacy = `-- name: CountComponentsLegacy :one
SELECT COUNT(*)
FROM components_legacy
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (
    $2::uuid IS NULL
      OR folder_id = $2
    )
  AND (
    $3::text IS NULL
      OR component_type = $3
    )
`

type CountComponentsLegacyParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	FolderID      pgtype.UUID `json:"folder_id"`
	ComponentType pgtype.Text `json:"component_type"`
}

func (q *Queries) CountComponentsLegacy(ctx context.Context, arg CountComponentsLegacyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComponentsLegacy, arg.ProjectID, arg.FolderID, arg.ComponentType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComponentLegacy = `-- name: CreateComponentLegacy :one
INSERT INTO components_legacy (
    project_id,
    folder_id,
    identity,
    display_name,
    description,
    component_type,
    source,
    source_format,
    props_schema,
    bindings,
    meta,
    active
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9,
           $10,
           $11,
           $12
       )
    RETURNING id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
`

type CreateComponentLegacyParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	FolderID      uuid.UUID   `json:"folder_id"`
	Identity      string      `json:"identity"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	ComponentType string      `json:"component_type"`
	Source        string      `json:"source"`
	SourceFormat  string      `json:"source_format"`
	PropsSchema   []byte      `json:"props_schema"`
	Bindings      []byte      `json:"bindings"`
	Meta          []byte      `json:"meta"`
	Active        bool        `json:"active"`
}

func (q *Queries) CreateComponentLegacy(ctx context.Context, arg CreateComponentLegacyParams) (ComponentLegacy, error) {
	row := q.db.QueryRow(ctx, createComponentLegacy,
		arg.ProjectID,
		arg.FolderID,
		arg.Identity,
		arg.DisplayName,
		arg.Description,
		arg.ComponentType,
		arg.Source,
		arg.SourceFormat,
		arg.PropsSchema,
		arg.Bindings,
		arg.Meta,
		arg.Active,
	)
	var i ComponentLegacy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsComponentLegacyByIdentity = `-- name: ExistsComponentLegacyByIdentity :one
SELECT EXISTS (
    SELECT 1
    FROM components_legacy
    WHERE project_id = $1
      AND identity = $2
)
`

type ExistsComponentLegacyByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) ExistsComponentLegacyByIdentity(ctx context.Context, arg ExistsComponentLegacyByIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsComponentLegacyByIdentity, arg.ProjectID, arg.Identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getComponentLegacyByID = `-- name: GetComponentLegacyByID :one
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components_legacy
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetComponentLegacyByID(ctx context.Context, id uuid.UUID) (ComponentLegacy, error) {
	row := q.db.QueryRow(ctx, getComponentLegacyByID, id)
	var i ComponentLegacy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComponentLegacyByIdentity = `-- name: GetComponentLegacyByIdentity :one
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components_legacy
WHERE project_id = $1
  AND identity = $2
  AND deleted_at IS NULL
`

type GetComponentLegacyByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetComponentLegacyByIdentity(ctx context.Context, arg GetComponentLegacyByIdentityParams) (ComponentLegacy, error) {
	row := q.db.QueryRow(ctx, getComponentLegacyByIdentity, arg.ProjectID, arg.Identity)
	var i ComponentLegacy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComponentLegacyByIdentityIncludingDeleted = `-- name: GetComponentLegacyByIdentityIncludingDeleted :one
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components_legacy
WHERE project_id = $1
  AND identity = $2
`

type GetComponentLegacyByIdentityIncludingDeletedParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetComponentLegacyByIdentityIncludingDeleted(ctx context.Context, arg GetComponentLegacyByIdentityIncludingDeletedParams) (ComponentLegacy, error) {
	row := q.db.QueryRow(ctx, getComponentLegacyByIdentityIncludingDeleted, arg.ProjectID, arg.Identity)
	var i ComponentLegacy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteComponentLegacy = `-- name: HardDeleteComponentLegacy :execrows
DELETE FROM components_legacy
WHERE id = $1
`

func (q *Queries) HardDeleteComponentLegacy(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteComponentLegacy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listComponentsLegacy = `-- name: ListComponentsLegacy :many
SELECT id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
FROM components_legacy
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (
    $2::uuid IS NULL
      OR folder_id = $2
    )
  AND (
    $3::text IS NULL
      OR component_type = $3
    )
ORDER BY created_at DESC
`

type ListComponentsLegacyParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	FolderID      pgtype.UUID `json:"folder_id"`
	ComponentType pgtype.Text `json:"component_type"`
}

func (q *Queries) ListComponentsLegacy(ctx context.Context, arg ListComponentsLegacyParams) ([]ComponentLegacy, error) {
	rows, err := q.db.Query(ctx, listComponentsLegacy, arg.ProjectID, arg.FolderID, arg.ComponentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComponentLegacy
	for rows.Next() {
		var i ComponentLegacy
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Identity,
			&i.DisplayName,
			&i.Description,
			&i.ComponentType,
			&i.Source,
			&i.SourceFormat,
			&i.PropsSchema,
			&i.Bindings,
			&i.Meta,
			&i.Active,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreComponentLegacy = `-- name: RestoreComponentLegacy :execrows
UPDATE components_legacy
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreComponentLegacy(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreComponentLegacy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteComponentLegacy = `-- name: SoftDeleteComponentLegacy :execrows
UPDATE components_legacy
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComponentLegacy(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComponentLegacy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComponentLegacy = `-- name: UpdateComponentLegacy :one
UPDATE components_legacy
SET
    folder_id = $1,
    display_name = $2,
    description = $3,
    component_type = $4,
    source = $5,
    source_format = $6,
    props_schema = $7,
    bindings = $8,
    meta = $9,
    active = $10,
    updated_at = NOW()
WHERE id = $11
  AND deleted_at IS NULL
    RETURNING id, project_id, folder_id, identity, display_name, description, component_type, source, source_format, props_schema, bindings, meta, active, deleted_at, created_at, updated_at
`

type UpdateComponentLegacyParams struct {
	FolderID      uuid.UUID   `json:"folder_id"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	ComponentType string      `json:"component_type"`
	Source        string      `json:"source"`
	SourceFormat  string      `json:"source_format"`
	PropsSchema   []byte      `json:"props_schema"`
	Bindings      []byte      `json:"bindings"`
	Meta          []byte      `json:"meta"`
	Active        bool        `json:"active"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateComponentLegacy(ctx context.Context, arg UpdateComponentLegacyParams) (ComponentLegacy, error) {
	row := q.db.QueryRow(ctx, updateComponentLegacy,
		arg.FolderID,
		arg.DisplayName,
		arg.Description,
		arg.ComponentType,
		arg.Source,
		arg.SourceFormat,
		arg.PropsSchema,
		arg.Bindings,
		arg.Meta,
		arg.Active,
		arg.ID,
	)
	var i ComponentLegacy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ComponentType,
		&i.Source,
		&i.SourceFormat,
		&i.PropsSchema,
		&i.Bindings,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
