// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: converter.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countConverters = `-- name: CountConverters :one
SELECT COUNT(*)
FROM converters
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (
    $2::uuid IS NULL
      OR folder_id = $2
    )
`

type CountConvertersParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	FolderID  pgtype.UUID `json:"folder_id"`
}

func (q *Queries) CountConverters(ctx context.Context, arg CountConvertersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countConverters, arg.ProjectID, arg.FolderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConverter = `-- name: CreateConverter :one
INSERT INTO converters (
    project_id,
    folder_id,
    identity,
    display_name,
    description,
    converter_type,
    source,
    is_system,
    meta,
    active
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8,
           $9,
           $10
       )
    RETURNING id, project_id, folder_id, identity, display_name, description, converter_type, source, is_system, meta, active, deleted_at, created_at, updated_at
`

type CreateConverterParams struct {
	ProjectID     uuid.UUID   `json:"project_id"`
	FolderID      uuid.UUID   `json:"folder_id"`
	Identity      string      `json:"identity"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	ConverterType string      `json:"converter_type"`
	Source        []byte      `json:"source"`
	IsSystem      bool        `json:"is_system"`
	Meta          []byte      `json:"meta"`
	Active        bool        `json:"active"`
}

func (q *Queries) CreateConverter(ctx context.Context, arg CreateConverterParams) (Converter, error) {
	row := q.db.QueryRow(ctx, createConverter,
		arg.ProjectID,
		arg.FolderID,
		arg.Identity,
		arg.DisplayName,
		arg.Description,
		arg.ConverterType,
		arg.Source,
		arg.IsSystem,
		arg.Meta,
		arg.Active,
	)
	var i Converter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ConverterType,
		&i.Source,
		&i.IsSystem,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsConverterByIdentity = `-- name: ExistsConverterByIdentity :one
SELECT EXISTS (
    SELECT 1
    FROM converters
    WHERE project_id = $1
      AND identity = $2
)
`

type ExistsConverterByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) ExistsConverterByIdentity(ctx context.Context, arg ExistsConverterByIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsConverterByIdentity, arg.ProjectID, arg.Identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getConverterByID = `-- name: GetConverterByID :one
SELECT id, project_id, folder_id, identity, display_name, description, converter_type, source, is_system, meta, active, deleted_at, created_at, updated_at
FROM converters
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetConverterByID(ctx context.Context, id uuid.UUID) (Converter, error) {
	row := q.db.QueryRow(ctx, getConverterByID, id)
	var i Converter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ConverterType,
		&i.Source,
		&i.IsSystem,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConverterByIdentity = `-- name: GetConverterByIdentity :one
SELECT id, project_id, folder_id, identity, display_name, description, converter_type, source, is_system, meta, active, deleted_at, created_at, updated_at
FROM converters
WHERE project_id = $1
  AND identity = $2
  AND deleted_at IS NULL
`

type GetConverterByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetConverterByIdentity(ctx context.Context, arg GetConverterByIdentityParams) (Converter, error) {
	row := q.db.QueryRow(ctx, getConverterByIdentity, arg.ProjectID, arg.Identity)
	var i Converter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ConverterType,
		&i.Source,
		&i.IsSystem,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConverterByIdentityIncludingDeleted = `-- name: GetConverterByIdentityIncludingDeleted :one
SELECT id, project_id, folder_id, identity, display_name, description, converter_type, source, is_system, meta, active, deleted_at, created_at, updated_at
FROM converters
WHERE project_id = $1
  AND identity = $2
`

type GetConverterByIdentityIncludingDeletedParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetConverterByIdentityIncludingDeleted(ctx context.Context, arg GetConverterByIdentityIncludingDeletedParams) (Converter, error) {
	row := q.db.QueryRow(ctx, getConverterByIdentityIncludingDeleted, arg.ProjectID, arg.Identity)
	var i Converter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ConverterType,
		&i.Source,
		&i.IsSystem,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteConverter = `-- name: HardDeleteConverter :execrows
DELETE FROM converters
WHERE id = $1
`

func (q *Queries) HardDeleteConverter(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteConverter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConverters = `-- name: ListConverters :many
SELECT id, project_id, folder_id, identity, display_name, description, converter_type, source, is_system, meta, active, deleted_at, created_at, updated_at
FROM converters
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (
    $2::uuid IS NULL
      OR folder_id = $2
    )
ORDER BY created_at DESC
`

type ListConvertersParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	FolderID  pgtype.UUID `json:"folder_id"`
}

func (q *Queries) ListConverters(ctx context.Context, arg ListConvertersParams) ([]Converter, error) {
	rows, err := q.db.Query(ctx, listConverters, arg.ProjectID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Converter
	for rows.Next() {
		var i Converter
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Identity,
			&i.DisplayName,
			&i.Description,
			&i.ConverterType,
			&i.Source,
			&i.IsSystem,
			&i.Meta,
			&i.Active,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreConverter = `-- name: RestoreConverter :execrows
UPDATE converters
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreConverter(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreConverter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteConverter = `-- name: SoftDeleteConverter :execrows
UPDATE converters
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteConverter(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteConverter, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateConverter = `-- name: UpdateConverter :one
UPDATE converters
SET
    folder_id = $1,
    display_name = $2,
    description = $3,
    converter_type = $4,
    source = $5,
    is_system = $6,
    meta = $7,
    active = $8,
    updated_at = NOW()
WHERE id = $9
  AND deleted_at IS NULL
    RETURNING id, project_id, folder_id, identity, display_name, description, converter_type, source, is_system, meta, active, deleted_at, created_at, updated_at
`

type UpdateConverterParams struct {
	FolderID      uuid.UUID   `json:"folder_id"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
	ConverterType string      `json:"converter_type"`
	Source        []byte      `json:"source"`
	IsSystem      bool        `json:"is_system"`
	Meta          []byte      `json:"meta"`
	Active        bool        `json:"active"`
	ID            uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateConverter(ctx context.Context, arg UpdateConverterParams) (Converter, error) {
	row := q.db.QueryRow(ctx, updateConverter,
		arg.FolderID,
		arg.DisplayName,
		arg.Description,
		arg.ConverterType,
		arg.Source,
		arg.IsSystem,
		arg.Meta,
		arg.Active,
		arg.ID,
	)
	var i Converter
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ConverterType,
		&i.Source,
		&i.IsSystem,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
