// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_view.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDataViews = `-- name: CountDataViews :one
SELECT COUNT(*)
FROM data_views
WHERE data_views.project_id = $1
  AND data_views.deleted_at IS NULL
  AND (
    $2::uuid IS NULL
    OR data_views.folder_id = $2
  )
  AND (
    $3::uuid IS NULL
    OR data_views.query_id = $3
  )
  AND EXISTS (
    SELECT 1
    FROM queries
    WHERE queries.id = data_views.query_id
      AND queries.deleted_at IS NULL
  )
`

type CountDataViewsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	FolderID  pgtype.UUID `json:"folder_id"`
	QueryID   pgtype.UUID `json:"query_id"`
}

func (q *Queries) CountDataViews(ctx context.Context, arg CountDataViewsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDataViews, arg.ProjectID, arg.FolderID, arg.QueryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDataView = `-- name: CreateDataView :one
INSERT INTO data_views (
    project_id,
    folder_id,
    query_id,
    identity,
    display_name,
    description,
    view_type,
    source,
    input_schema,
    output_schema,
    meta,
    active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, project_id, folder_id, query_id, identity, display_name, description, view_type, source, input_schema, output_schema, meta, active, deleted_at, created_at, updated_at
`

type CreateDataViewParams struct {
	ProjectID    uuid.UUID   `json:"project_id"`
	FolderID     uuid.UUID   `json:"folder_id"`
	QueryID      uuid.UUID   `json:"query_id"`
	Identity     string      `json:"identity"`
	DisplayName  string      `json:"display_name"`
	Description  pgtype.Text `json:"description"`
	ViewType     string      `json:"view_type"`
	Source       []byte      `json:"source"`
	InputSchema  []byte      `json:"input_schema"`
	OutputSchema []byte      `json:"output_schema"`
	Meta         []byte      `json:"meta"`
	Active       bool        `json:"active"`
}

func (q *Queries) CreateDataView(ctx context.Context, arg CreateDataViewParams) (DataView, error) {
	row := q.db.QueryRow(ctx, createDataView,
		arg.ProjectID,
		arg.FolderID,
		arg.QueryID,
		arg.Identity,
		arg.DisplayName,
		arg.Description,
		arg.ViewType,
		arg.Source,
		arg.InputSchema,
		arg.OutputSchema,
		arg.Meta,
		arg.Active,
	)
	var i DataView
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.QueryID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ViewType,
		&i.Source,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsDataViewByIdentity = `-- name: ExistsDataViewByIdentity :one
SELECT EXISTS (
    SELECT 1
    FROM data_views
    WHERE project_id = $1
      AND identity = $2
)
`

type ExistsDataViewByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) ExistsDataViewByIdentity(ctx context.Context, arg ExistsDataViewByIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsDataViewByIdentity, arg.ProjectID, arg.Identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getDataViewByID = `-- name: GetDataViewByID :one
SELECT id, project_id, folder_id, query_id, identity, display_name, description, view_type, source, input_schema, output_schema, meta, active, deleted_at, created_at, updated_at
FROM data_views
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDataViewByID(ctx context.Context, id uuid.UUID) (DataView, error) {
	row := q.db.QueryRow(ctx, getDataViewByID, id)
	var i DataView
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.QueryID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ViewType,
		&i.Source,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataViewByIdentity = `-- name: GetDataViewByIdentity :one
SELECT id, project_id, folder_id, query_id, identity, display_name, description, view_type, source, input_schema, output_schema, meta, active, deleted_at, created_at, updated_at
FROM data_views
WHERE project_id = $1
  AND identity = $2
  AND deleted_at IS NULL
`

type GetDataViewByIdentityParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetDataViewByIdentity(ctx context.Context, arg GetDataViewByIdentityParams) (DataView, error) {
	row := q.db.QueryRow(ctx, getDataViewByIdentity, arg.ProjectID, arg.Identity)
	var i DataView
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.QueryID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ViewType,
		&i.Source,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDataViewByIdentityIncludingDeleted = `-- name: GetDataViewByIdentityIncludingDeleted :one
SELECT id, project_id, folder_id, query_id, identity, display_name, description, view_type, source, input_schema, output_schema, meta, active, deleted_at, created_at, updated_at
FROM data_views
WHERE project_id = $1
  AND identity = $2
`

type GetDataViewByIdentityIncludingDeletedParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Identity  string    `json:"identity"`
}

func (q *Queries) GetDataViewByIdentityIncludingDeleted(ctx context.Context, arg GetDataViewByIdentityIncludingDeletedParams) (DataView, error) {
	row := q.db.QueryRow(ctx, getDataViewByIdentityIncludingDeleted, arg.ProjectID, arg.Identity)
	var i DataView
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.QueryID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ViewType,
		&i.Source,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteDataView = `-- name: HardDeleteDataView :execrows
DELETE FROM data_views
WHERE id = $1
`

func (q *Queries) HardDeleteDataView(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteDataView, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDataViews = `-- name: ListDataViews :many
SELECT id, project_id, folder_id, query_id, identity, display_name, description, view_type, source, input_schema, output_schema, meta, active, deleted_at, created_at, updated_at
FROM data_views
WHERE data_views.project_id = $1
  AND data_views.deleted_at IS NULL
  AND (
    $2::uuid IS NULL
    OR data_views.folder_id = $2
  )
  AND (
    $3::uuid IS NULL
    OR data_views.query_id = $3
  )
  AND EXISTS (
    SELECT 1
    FROM queries
    WHERE queries.id = data_views.query_id
      AND queries.deleted_at IS NULL
  )
ORDER BY data_views.created_at DESC
`

type ListDataViewsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	FolderID  pgtype.UUID `json:"folder_id"`
	QueryID   pgtype.UUID `json:"query_id"`
}

func (q *Queries) ListDataViews(ctx context.Context, arg ListDataViewsParams) ([]DataView, error) {
	rows, err := q.db.Query(ctx, listDataViews, arg.ProjectID, arg.FolderID, arg.QueryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataView
	for rows.Next() {
		var i DataView
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.QueryID,
			&i.Identity,
			&i.DisplayName,
			&i.Description,
			&i.ViewType,
			&i.Source,
			&i.InputSchema,
			&i.OutputSchema,
			&i.Meta,
			&i.Active,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDataView = `-- name: RestoreDataView :execrows
UPDATE data_views
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreDataView(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreDataView, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteDataView = `-- name: SoftDeleteDataView :execrows
UPDATE data_views
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDataView(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDataView, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDataView = `-- name: UpdateDataView :one
UPDATE data_views
SET
    folder_id = $1,
    query_id = $2,
    display_name = $3,
    description = $4,
    view_type = $5,
    source = $6,
    input_schema = $7,
    output_schema = $8,
    meta = $9,
    active = $10,
    updated_at = NOW()
WHERE id = $11
  AND deleted_at IS NULL
RETURNING id, project_id, folder_id, query_id, identity, display_name, description, view_type, source, input_schema, output_schema, meta, active, deleted_at, created_at, updated_at
`

type UpdateDataViewParams struct {
	FolderID     uuid.UUID   `json:"folder_id"`
	QueryID      uuid.UUID   `json:"query_id"`
	DisplayName  string      `json:"display_name"`
	Description  pgtype.Text `json:"description"`
	ViewType     string      `json:"view_type"`
	Source       []byte      `json:"source"`
	InputSchema  []byte      `json:"input_schema"`
	OutputSchema []byte      `json:"output_schema"`
	Meta         []byte      `json:"meta"`
	Active       bool        `json:"active"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDataView(ctx context.Context, arg UpdateDataViewParams) (DataView, error) {
	row := q.db.QueryRow(ctx, updateDataView,
		arg.FolderID,
		arg.QueryID,
		arg.DisplayName,
		arg.Description,
		arg.ViewType,
		arg.Source,
		arg.InputSchema,
		arg.OutputSchema,
		arg.Meta,
		arg.Active,
		arg.ID,
	)
	var i DataView
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.QueryID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ViewType,
		&i.Source,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Meta,
		&i.Active,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
