// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain_dependency.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDomainDependency = `-- name: CreateDomainDependency :exec
INSERT INTO domain_dependencies (
    workspace_id,
    owner_type,
    owner_id,
    dependency_type,
    dependency_identity,
    source_path
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateDomainDependencyParams struct {
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	OwnerType          string    `json:"owner_type"`
	OwnerID            uuid.UUID `json:"owner_id"`
	DependencyType     string    `json:"dependency_type"`
	DependencyIdentity string    `json:"dependency_identity"`
	SourcePath         string    `json:"source_path"`
}

func (q *Queries) CreateDomainDependency(ctx context.Context, arg CreateDomainDependencyParams) error {
	_, err := q.db.Exec(ctx, createDomainDependency,
		arg.WorkspaceID,
		arg.OwnerType,
		arg.OwnerID,
		arg.DependencyType,
		arg.DependencyIdentity,
		arg.SourcePath,
	)
	return err
}

const deleteDomainDependenciesForOwner = `-- name: DeleteDomainDependenciesForOwner :exec
DELETE FROM domain_dependencies
WHERE workspace_id = $1
  AND owner_type = $2
  AND owner_id = $3
`

type DeleteDomainDependenciesForOwnerParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	OwnerType   string    `json:"owner_type"`
	OwnerID     uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteDomainDependenciesForOwner(ctx context.Context, arg DeleteDomainDependenciesForOwnerParams) error {
	_, err := q.db.Exec(ctx, deleteDomainDependenciesForOwner, arg.WorkspaceID, arg.OwnerType, arg.OwnerID)
	return err
}

const deleteDomainDependencyStateForOwner = `-- name: DeleteDomainDependencyStateForOwner :exec
DELETE FROM domain_dependency_states
WHERE workspace_id = $1
  AND owner_type = $2
  AND owner_id = $3
`

type DeleteDomainDependencyStateForOwnerParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	OwnerType   string    `json:"owner_type"`
	OwnerID     uuid.UUID `json:"owner_id"`
}

func (q *Queries) DeleteDomainDependencyStateForOwner(ctx context.Context, arg DeleteDomainDependencyStateForOwnerParams) error {
	_, err := q.db.Exec(ctx, deleteDomainDependencyStateForOwner, arg.WorkspaceID, arg.OwnerType, arg.OwnerID)
	return err
}

const listDomainDependencyUsages = `-- name: ListDomainDependencyUsages :many
SELECT
    dependency.owner_type,
    dependency.owner_id,
    state.owner_identity,
    dependency.source_path,
    state.verification_state,
    COUNT(*) OVER() AS total
FROM domain_dependencies AS dependency
JOIN domain_dependency_states AS state
  ON state.workspace_id = dependency.workspace_id
 AND state.owner_type = dependency.owner_type
 AND state.owner_id = dependency.owner_id
WHERE dependency.workspace_id = $1
  AND dependency.dependency_type = $2
  AND dependency.dependency_identity = $3
ORDER BY dependency.owner_type, state.owner_identity, dependency.source_path
LIMIT $5
OFFSET $4
`

type ListDomainDependencyUsagesParams struct {
	WorkspaceID        uuid.UUID `json:"workspace_id"`
	DependencyType     string    `json:"dependency_type"`
	DependencyIdentity string    `json:"dependency_identity"`
	OffsetCount        int32     `json:"offset_count"`
	LimitCount         int32     `json:"limit_count"`
}

type ListDomainDependencyUsagesRow struct {
	OwnerType         string    `json:"owner_type"`
	OwnerID           uuid.UUID `json:"owner_id"`
	OwnerIdentity     string    `json:"owner_identity"`
	SourcePath        string    `json:"source_path"`
	VerificationState string    `json:"verification_state"`
	Total             int64     `json:"total"`
}

func (q *Queries) ListDomainDependencyUsages(ctx context.Context, arg ListDomainDependencyUsagesParams) ([]ListDomainDependencyUsagesRow, error) {
	rows, err := q.db.Query(ctx, listDomainDependencyUsages,
		arg.WorkspaceID,
		arg.DependencyType,
		arg.DependencyIdentity,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDomainDependencyUsagesRow
	for rows.Next() {
		var i ListDomainDependencyUsagesRow
		if err := rows.Scan(
			&i.OwnerType,
			&i.OwnerID,
			&i.OwnerIdentity,
			&i.SourcePath,
			&i.VerificationState,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDomainDependencyState = `-- name: UpsertDomainDependencyState :exec
INSERT INTO domain_dependency_states (
    workspace_id,
    owner_type,
    owner_id,
    owner_identity,
    verification_state,
    verification_error
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (workspace_id, owner_type, owner_id)
DO UPDATE SET
    owner_identity = EXCLUDED.owner_identity,
    verification_state = EXCLUDED.verification_state,
    verification_error = EXCLUDED.verification_error,
    updated_at = NOW()
`

type UpsertDomainDependencyStateParams struct {
	WorkspaceID       uuid.UUID   `json:"workspace_id"`
	OwnerType         string      `json:"owner_type"`
	OwnerID           uuid.UUID   `json:"owner_id"`
	OwnerIdentity     string      `json:"owner_identity"`
	VerificationState string      `json:"verification_state"`
	VerificationError pgtype.Text `json:"verification_error"`
}

func (q *Queries) UpsertDomainDependencyState(ctx context.Context, arg UpsertDomainDependencyStateParams) error {
	_, err := q.db.Exec(ctx, upsertDomainDependencyState,
		arg.WorkspaceID,
		arg.OwnerType,
		arg.OwnerID,
		arg.OwnerIdentity,
		arg.VerificationState,
		arg.VerificationError,
	)
	return err
}
