// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folder.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFoldersByProjectAndEntityType = `-- name: CountFoldersByProjectAndEntityType :one
SELECT COUNT(*)
FROM folders
WHERE project_id IS NOT DISTINCT FROM $1
  AND entity_type = $2
  AND deleted_at IS NULL
`

type CountFoldersByProjectAndEntityTypeParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EntityType string      `json:"entity_type"`
}

func (q *Queries) CountFoldersByProjectAndEntityType(ctx context.Context, arg CountFoldersByProjectAndEntityTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFoldersByProjectAndEntityType, arg.ProjectID, arg.EntityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
    project_id,
    entity_type,
    identity,
    display_name,
    description,
    parent_id,
    is_root,
    is_system,
    meta
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, project_id, entity_type, identity, display_name, description, parent_id, is_root, is_system, deleted_at, meta, created_at, updated_at
`

type CreateFolderParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	EntityType  string      `json:"entity_type"`
	Identity    string      `json:"identity"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	IsRoot      bool        `json:"is_root"`
	IsSystem    bool        `json:"is_system"`
	Meta        []byte      `json:"meta"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ProjectID,
		arg.EntityType,
		arg.Identity,
		arg.DisplayName,
		arg.Description,
		arg.ParentID,
		arg.IsRoot,
		arg.IsSystem,
		arg.Meta,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityType,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ParentID,
		&i.IsRoot,
		&i.IsSystem,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsFolderByProjectEntityIdentity = `-- name: ExistsFolderByProjectEntityIdentity :one
SELECT EXISTS(
    SELECT 1
    FROM folders
    WHERE project_id IS NOT DISTINCT FROM $1
      AND entity_type = $2
      AND identity = $3
)
`

type ExistsFolderByProjectEntityIdentityParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EntityType string      `json:"entity_type"`
	Identity   string      `json:"identity"`
}

func (q *Queries) ExistsFolderByProjectEntityIdentity(ctx context.Context, arg ExistsFolderByProjectEntityIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsFolderByProjectEntityIdentity, arg.ProjectID, arg.EntityType, arg.Identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, project_id, entity_type, identity, display_name, description, parent_id, is_root, is_system, deleted_at, meta, created_at, updated_at
FROM folders
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityType,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ParentID,
		&i.IsRoot,
		&i.IsSystem,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByIDIncludingDeleted = `-- name: GetFolderByIDIncludingDeleted :one
SELECT id, project_id, entity_type, identity, display_name, description, parent_id, is_root, is_system, deleted_at, meta, created_at, updated_at
FROM folders
WHERE id = $1
`

func (q *Queries) GetFolderByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByIDIncludingDeleted, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityType,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ParentID,
		&i.IsRoot,
		&i.IsSystem,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByProjectEntityIdentity = `-- name: GetFolderByProjectEntityIdentity :one
SELECT id, project_id, entity_type, identity, display_name, description, parent_id, is_root, is_system, deleted_at, meta, created_at, updated_at
FROM folders
WHERE project_id IS NOT DISTINCT FROM $1
  AND entity_type = $2
  AND identity = $3
  AND deleted_at IS NULL
`

type GetFolderByProjectEntityIdentityParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EntityType string      `json:"entity_type"`
	Identity   string      `json:"identity"`
}

func (q *Queries) GetFolderByProjectEntityIdentity(ctx context.Context, arg GetFolderByProjectEntityIdentityParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByProjectEntityIdentity, arg.ProjectID, arg.EntityType, arg.Identity)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityType,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ParentID,
		&i.IsRoot,
		&i.IsSystem,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByProjectEntityIdentityIncludingDeleted = `-- name: GetFolderByProjectEntityIdentityIncludingDeleted :one
SELECT id, project_id, entity_type, identity, display_name, description, parent_id, is_root, is_system, deleted_at, meta, created_at, updated_at
FROM folders
WHERE project_id IS NOT DISTINCT FROM $1
  AND entity_type = $2
  AND identity = $3
`

type GetFolderByProjectEntityIdentityIncludingDeletedParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EntityType string      `json:"entity_type"`
	Identity   string      `json:"identity"`
}

func (q *Queries) GetFolderByProjectEntityIdentityIncludingDeleted(ctx context.Context, arg GetFolderByProjectEntityIdentityIncludingDeletedParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByProjectEntityIdentityIncludingDeleted, arg.ProjectID, arg.EntityType, arg.Identity)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityType,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ParentID,
		&i.IsRoot,
		&i.IsSystem,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteFolder = `-- name: HardDeleteFolder :execrows
DELETE FROM folders
WHERE id = $1
`

func (q *Queries) HardDeleteFolder(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteFolder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFoldersByProjectAndEntityType = `-- name: ListFoldersByProjectAndEntityType :many
SELECT id, project_id, entity_type, identity, display_name, description, parent_id, is_root, is_system, deleted_at, meta, created_at, updated_at
FROM folders
WHERE project_id IS NOT DISTINCT FROM $1
  AND entity_type = $2
  AND deleted_at IS NULL
ORDER BY is_root DESC, display_name ASC, created_at ASC
`

type ListFoldersByProjectAndEntityTypeParams struct {
	ProjectID  pgtype.UUID `json:"project_id"`
	EntityType string      `json:"entity_type"`
}

func (q *Queries) ListFoldersByProjectAndEntityType(ctx context.Context, arg ListFoldersByProjectAndEntityTypeParams) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByProjectAndEntityType, arg.ProjectID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityType,
			&i.Identity,
			&i.DisplayName,
			&i.Description,
			&i.ParentID,
			&i.IsRoot,
			&i.IsSystem,
			&i.DeletedAt,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreFolder = `-- name: RestoreFolder :execrows
UPDATE folders
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreFolder(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreFolder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteFolder = `-- name: SoftDeleteFolder :execrows
UPDATE folders
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteFolder(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFolder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET
    display_name = $2,
    description = $3,
    parent_id = $4,
    meta = $5,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, project_id, entity_type, identity, display_name, description, parent_id, is_root, is_system, deleted_at, meta, created_at, updated_at
`

type UpdateFolderParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Meta        []byte      `json:"meta"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolder,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.ParentID,
		arg.Meta,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityType,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.ParentID,
		&i.IsRoot,
		&i.IsSystem,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
