// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProject = `-- name: CountProject :one
SELECT COUNT(*)
FROM projects
WHERE deleted_at IS NULL
`

func (q *Queries) CountProject(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProject)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    identity,
    display_name,
    description,
    active,
    meta
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5
       )
    RETURNING id, identity, display_name, description, active, deleted_at, meta, created_at, updated_at
`

type CreateProjectParams struct {
	Identity    string      `json:"identity"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
	Meta        []byte      `json:"meta"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Identity,
		arg.DisplayName,
		arg.Description,
		arg.Active,
		arg.Meta,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsProjectByIdentity = `-- name: ExistsProjectByIdentity :one
SELECT EXISTS(
    SELECT 1
    FROM projects
    WHERE identity = $1
)
`

func (q *Queries) ExistsProjectByIdentity(ctx context.Context, identity string) (bool, error) {
	row := q.db.QueryRow(ctx, existsProjectByIdentity, identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, identity, display_name, description, active, deleted_at, meta, created_at, updated_at
FROM projects
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByIdentity = `-- name: GetProjectByIdentity :one
SELECT id, identity, display_name, description, active, deleted_at, meta, created_at, updated_at
FROM projects
WHERE identity = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectByIdentity(ctx context.Context, identity string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIdentity, identity)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByIdentityIncludingDeleted = `-- name: GetProjectByIdentityIncludingDeleted :one
SELECT id, identity, display_name, description, active, deleted_at, meta, created_at, updated_at
FROM projects
WHERE identity = $1
`

func (q *Queries) GetProjectByIdentityIncludingDeleted(ctx context.Context, identity string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIdentityIncludingDeleted, identity)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteProject = `-- name: HardDeleteProject :execrows
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) HardDeleteProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, identity, display_name, description, active, deleted_at, meta, created_at, updated_at
FROM projects
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Identity,
			&i.DisplayName,
			&i.Description,
			&i.Active,
			&i.DeletedAt,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProject = `-- name: RestoreProject :execrows
UPDATE projects
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    display_name = $2,
    description = $3,
    active = $4,
    meta = $5,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
    RETURNING id, identity, display_name, description, active, deleted_at, meta, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Active      bool        `json:"active"`
	Meta        []byte      `json:"meta"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.Active,
		arg.Meta,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
