// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProject = `-- name: CountProject :one
SELECT COUNT(*)
FROM projects
WHERE deleted_at IS NULL
`

func (q *Queries) CountProject(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProject)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    identity,
    display_name,
    extend_settings,
    settings_id,
    navigation_id,
    folder_id,
    allowed_environment_ids,
    meta
)
VALUES (
           $1,
           $2,
           $3,
           $4,
           $5,
           $6,
           $7,
           $8
       )
    RETURNING id, identity, display_name, extend_settings, settings_id, navigation_id, folder_id, allowed_environment_ids, deleted_at, meta, created_at, updated_at
`

type CreateProjectParams struct {
	Identity              string      `json:"identity"`
	DisplayName           string      `json:"display_name"`
	ExtendSettings        bool        `json:"extend_settings"`
	SettingsID            pgtype.UUID `json:"settings_id"`
	NavigationID          pgtype.UUID `json:"navigation_id"`
	FolderID              pgtype.UUID `json:"folder_id"`
	AllowedEnvironmentIds []uuid.UUID `json:"allowed_environment_ids"`
	Meta                  []byte      `json:"meta"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Identity,
		arg.DisplayName,
		arg.ExtendSettings,
		arg.SettingsID,
		arg.NavigationID,
		arg.FolderID,
		arg.AllowedEnvironmentIds,
		arg.Meta,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.ExtendSettings,
		&i.SettingsID,
		&i.NavigationID,
		&i.FolderID,
		&i.AllowedEnvironmentIds,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsProjectByIdentity = `-- name: ExistsProjectByIdentity :one
SELECT EXISTS(
    SELECT 1
    FROM projects
    WHERE identity = $1
      AND deleted_at IS NULL
)
`

func (q *Queries) ExistsProjectByIdentity(ctx context.Context, identity string) (bool, error) {
	row := q.db.QueryRow(ctx, existsProjectByIdentity, identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, identity, display_name, extend_settings, settings_id, navigation_id, folder_id, allowed_environment_ids, deleted_at, meta, created_at, updated_at
FROM projects
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.ExtendSettings,
		&i.SettingsID,
		&i.NavigationID,
		&i.FolderID,
		&i.AllowedEnvironmentIds,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByIdentity = `-- name: GetProjectByIdentity :one
SELECT id, identity, display_name, extend_settings, settings_id, navigation_id, folder_id, allowed_environment_ids, deleted_at, meta, created_at, updated_at
FROM projects
WHERE identity = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectByIdentity(ctx context.Context, identity string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIdentity, identity)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.ExtendSettings,
		&i.SettingsID,
		&i.NavigationID,
		&i.FolderID,
		&i.AllowedEnvironmentIds,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteProject = `-- name: HardDeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) HardDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteProject, id)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, identity, display_name, extend_settings, settings_id, navigation_id, folder_id, allowed_environment_ids, deleted_at, meta, created_at, updated_at
FROM projects
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Identity,
			&i.DisplayName,
			&i.ExtendSettings,
			&i.SettingsID,
			&i.NavigationID,
			&i.FolderID,
			&i.AllowedEnvironmentIds,
			&i.DeletedAt,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProjects = `-- name: RestoreProjects :exec
UPDATE projects
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) RestoreProjects(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreProjects, id)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    identity = $2,
    display_name = $3,
    extend_settings = $4,
    settings_id = $5,
    navigation_id = $6,
    folder_id = $7,
    allowed_environment_ids = $8,
    meta = $9,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
    RETURNING id, identity, display_name, extend_settings, settings_id, navigation_id, folder_id, allowed_environment_ids, deleted_at, meta, created_at, updated_at
`

type UpdateProjectParams struct {
	ID                    uuid.UUID   `json:"id"`
	Identity              string      `json:"identity"`
	DisplayName           string      `json:"display_name"`
	ExtendSettings        bool        `json:"extend_settings"`
	SettingsID            pgtype.UUID `json:"settings_id"`
	NavigationID          pgtype.UUID `json:"navigation_id"`
	FolderID              pgtype.UUID `json:"folder_id"`
	AllowedEnvironmentIds []uuid.UUID `json:"allowed_environment_ids"`
	Meta                  []byte      `json:"meta"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Identity,
		arg.DisplayName,
		arg.ExtendSettings,
		arg.SettingsID,
		arg.NavigationID,
		arg.FolderID,
		arg.AllowedEnvironmentIds,
		arg.Meta,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.ExtendSettings,
		&i.SettingsID,
		&i.NavigationID,
		&i.FolderID,
		&i.AllowedEnvironmentIds,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
