// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countQueries = `-- name: CountQueries :one
SELECT COUNT(*)
FROM queries
WHERE workspace_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
  AND (
    $3::uuid IS NULL
    OR folder_id = $3
  )
  AND (
    $4::text IS NULL
    OR query_type = $4
  )
`

type CountQueriesParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
	QueryType   pgtype.Text `json:"query_type"`
}

func (q *Queries) CountQueries(ctx context.Context, arg CountQueriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQueries,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.FolderID,
		arg.QueryType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuery = `-- name: CreateQuery :one
INSERT INTO queries (
    workspace_id,
    project_id,
    folder_id,
    identity,
    display_name,
    description,
    query_type,
    source,
    params,
    headers,
    auth,
    timeout_ms,
    mock_data,
    mock_data_enabled,
    meta,
    active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16
)
RETURNING id, workspace_id, project_id, folder_id, identity, display_name, description, query_type, source, params, headers, auth, timeout_ms, mock_data, mock_data_enabled, active, deleted_at, meta, created_at, updated_at
`

type CreateQueryParams struct {
	WorkspaceID     uuid.UUID   `json:"workspace_id"`
	ProjectID       uuid.UUID   `json:"project_id"`
	FolderID        uuid.UUID   `json:"folder_id"`
	Identity        string      `json:"identity"`
	DisplayName     string      `json:"display_name"`
	Description     pgtype.Text `json:"description"`
	QueryType       string      `json:"query_type"`
	Source          []byte      `json:"source"`
	Params          []byte      `json:"params"`
	Headers         []byte      `json:"headers"`
	Auth            []byte      `json:"auth"`
	TimeoutMs       pgtype.Int4 `json:"timeout_ms"`
	MockData        []byte      `json:"mock_data"`
	MockDataEnabled bool        `json:"mock_data_enabled"`
	Meta            []byte      `json:"meta"`
	Active          bool        `json:"active"`
}

func (q *Queries) CreateQuery(ctx context.Context, arg CreateQueryParams) (Query, error) {
	row := q.db.QueryRow(ctx, createQuery,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.FolderID,
		arg.Identity,
		arg.DisplayName,
		arg.Description,
		arg.QueryType,
		arg.Source,
		arg.Params,
		arg.Headers,
		arg.Auth,
		arg.TimeoutMs,
		arg.MockData,
		arg.MockDataEnabled,
		arg.Meta,
		arg.Active,
	)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.QueryType,
		&i.Source,
		&i.Params,
		&i.Headers,
		&i.Auth,
		&i.TimeoutMs,
		&i.MockData,
		&i.MockDataEnabled,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsActiveQueryByIdentityOutsideProject = `-- name: ExistsActiveQueryByIdentityOutsideProject :one
SELECT EXISTS (
    SELECT 1
    FROM queries
    WHERE workspace_id = $1
      AND project_id <> $2
      AND identity = $3
      AND deleted_at IS NULL
)
`

type ExistsActiveQueryByIdentityOutsideProjectParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Identity    string    `json:"identity"`
}

func (q *Queries) ExistsActiveQueryByIdentityOutsideProject(ctx context.Context, arg ExistsActiveQueryByIdentityOutsideProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsActiveQueryByIdentityOutsideProject, arg.WorkspaceID, arg.ProjectID, arg.Identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsQueryByIdentity = `-- name: ExistsQueryByIdentity :one
SELECT EXISTS (
    SELECT 1
    FROM queries
    WHERE workspace_id = $1
      AND project_id = $2
      AND identity = $3
)
`

type ExistsQueryByIdentityParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Identity    string    `json:"identity"`
}

func (q *Queries) ExistsQueryByIdentity(ctx context.Context, arg ExistsQueryByIdentityParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsQueryByIdentity, arg.WorkspaceID, arg.ProjectID, arg.Identity)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getQueryByID = `-- name: GetQueryByID :one
SELECT id, workspace_id, project_id, folder_id, identity, display_name, description, query_type, source, params, headers, auth, timeout_ms, mock_data, mock_data_enabled, active, deleted_at, meta, created_at, updated_at
FROM queries
WHERE id = $1
  AND workspace_id = $2
  AND deleted_at IS NULL
`

type GetQueryByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetQueryByID(ctx context.Context, arg GetQueryByIDParams) (Query, error) {
	row := q.db.QueryRow(ctx, getQueryByID, arg.ID, arg.WorkspaceID)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.QueryType,
		&i.Source,
		&i.Params,
		&i.Headers,
		&i.Auth,
		&i.TimeoutMs,
		&i.MockData,
		&i.MockDataEnabled,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueryByIDIncludingDeleted = `-- name: GetQueryByIDIncludingDeleted :one
SELECT id, workspace_id, project_id, folder_id, identity, display_name, description, query_type, source, params, headers, auth, timeout_ms, mock_data, mock_data_enabled, active, deleted_at, meta, created_at, updated_at
FROM queries
WHERE id = $1
  AND workspace_id = $2
`

type GetQueryByIDIncludingDeletedParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetQueryByIDIncludingDeleted(ctx context.Context, arg GetQueryByIDIncludingDeletedParams) (Query, error) {
	row := q.db.QueryRow(ctx, getQueryByIDIncludingDeleted, arg.ID, arg.WorkspaceID)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.QueryType,
		&i.Source,
		&i.Params,
		&i.Headers,
		&i.Auth,
		&i.TimeoutMs,
		&i.MockData,
		&i.MockDataEnabled,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueryByIdentity = `-- name: GetQueryByIdentity :one
SELECT id, workspace_id, project_id, folder_id, identity, display_name, description, query_type, source, params, headers, auth, timeout_ms, mock_data, mock_data_enabled, active, deleted_at, meta, created_at, updated_at
FROM queries
WHERE workspace_id = $1
  AND project_id = $2
  AND identity = $3
  AND deleted_at IS NULL
`

type GetQueryByIdentityParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Identity    string    `json:"identity"`
}

func (q *Queries) GetQueryByIdentity(ctx context.Context, arg GetQueryByIdentityParams) (Query, error) {
	row := q.db.QueryRow(ctx, getQueryByIdentity, arg.WorkspaceID, arg.ProjectID, arg.Identity)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.QueryType,
		&i.Source,
		&i.Params,
		&i.Headers,
		&i.Auth,
		&i.TimeoutMs,
		&i.MockData,
		&i.MockDataEnabled,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueryByIdentityIncludingDeleted = `-- name: GetQueryByIdentityIncludingDeleted :one
SELECT id, workspace_id, project_id, folder_id, identity, display_name, description, query_type, source, params, headers, auth, timeout_ms, mock_data, mock_data_enabled, active, deleted_at, meta, created_at, updated_at
FROM queries
WHERE workspace_id = $1
  AND project_id = $2
  AND identity = $3
`

type GetQueryByIdentityIncludingDeletedParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Identity    string    `json:"identity"`
}

func (q *Queries) GetQueryByIdentityIncludingDeleted(ctx context.Context, arg GetQueryByIdentityIncludingDeletedParams) (Query, error) {
	row := q.db.QueryRow(ctx, getQueryByIdentityIncludingDeleted, arg.WorkspaceID, arg.ProjectID, arg.Identity)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.QueryType,
		&i.Source,
		&i.Params,
		&i.Headers,
		&i.Auth,
		&i.TimeoutMs,
		&i.MockData,
		&i.MockDataEnabled,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteQuery = `-- name: HardDeleteQuery :execrows
DELETE FROM queries
WHERE id = $1
  AND workspace_id = $2
`

type HardDeleteQueryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) HardDeleteQuery(ctx context.Context, arg HardDeleteQueryParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteQuery, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listQueries = `-- name: ListQueries :many
SELECT id, workspace_id, project_id, folder_id, identity, display_name, description, query_type, source, params, headers, auth, timeout_ms, mock_data, mock_data_enabled, active, deleted_at, meta, created_at, updated_at
FROM queries
WHERE workspace_id = $1
  AND project_id = $2
  AND deleted_at IS NULL
  AND (
    $3::uuid IS NULL
    OR folder_id = $3
  )
  AND (
    $4::text IS NULL
    OR query_type = $4
  )
ORDER BY created_at DESC
`

type ListQueriesParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
	QueryType   pgtype.Text `json:"query_type"`
}

func (q *Queries) ListQueries(ctx context.Context, arg ListQueriesParams) ([]Query, error) {
	rows, err := q.db.Query(ctx, listQueries,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.FolderID,
		arg.QueryType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Query
	for rows.Next() {
		var i Query
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.FolderID,
			&i.Identity,
			&i.DisplayName,
			&i.Description,
			&i.QueryType,
			&i.Source,
			&i.Params,
			&i.Headers,
			&i.Auth,
			&i.TimeoutMs,
			&i.MockData,
			&i.MockDataEnabled,
			&i.Active,
			&i.DeletedAt,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreQuery = `-- name: RestoreQuery :execrows
UPDATE queries
SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND workspace_id = $2
  AND deleted_at IS NOT NULL
`

type RestoreQueryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) RestoreQuery(ctx context.Context, arg RestoreQueryParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreQuery, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteQuery = `-- name: SoftDeleteQuery :execrows
UPDATE queries
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND workspace_id = $2
  AND deleted_at IS NULL
`

type SoftDeleteQueryParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) SoftDeleteQuery(ctx context.Context, arg SoftDeleteQueryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteQuery, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateQuery = `-- name: UpdateQuery :one
UPDATE queries
SET
    folder_id = $1,
    display_name = $2,
    description = $3,
    query_type = $4,
    source = $5,
    params = $6,
    headers = $7,
    auth = $8,
    timeout_ms = $9,
    mock_data = $10,
    mock_data_enabled = $11,
    meta = $12,
    active = $13,
    updated_at = NOW()
WHERE id = $14
  AND workspace_id = $15
  AND deleted_at IS NULL
RETURNING id, workspace_id, project_id, folder_id, identity, display_name, description, query_type, source, params, headers, auth, timeout_ms, mock_data, mock_data_enabled, active, deleted_at, meta, created_at, updated_at
`

type UpdateQueryParams struct {
	FolderID        uuid.UUID   `json:"folder_id"`
	DisplayName     string      `json:"display_name"`
	Description     pgtype.Text `json:"description"`
	QueryType       string      `json:"query_type"`
	Source          []byte      `json:"source"`
	Params          []byte      `json:"params"`
	Headers         []byte      `json:"headers"`
	Auth            []byte      `json:"auth"`
	TimeoutMs       pgtype.Int4 `json:"timeout_ms"`
	MockData        []byte      `json:"mock_data"`
	MockDataEnabled bool        `json:"mock_data_enabled"`
	Meta            []byte      `json:"meta"`
	Active          bool        `json:"active"`
	ID              uuid.UUID   `json:"id"`
	WorkspaceID     uuid.UUID   `json:"workspace_id"`
}

func (q *Queries) UpdateQuery(ctx context.Context, arg UpdateQueryParams) (Query, error) {
	row := q.db.QueryRow(ctx, updateQuery,
		arg.FolderID,
		arg.DisplayName,
		arg.Description,
		arg.QueryType,
		arg.Source,
		arg.Params,
		arg.Headers,
		arg.Auth,
		arg.TimeoutMs,
		arg.MockData,
		arg.MockDataEnabled,
		arg.Meta,
		arg.Active,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Query
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.FolderID,
		&i.Identity,
		&i.DisplayName,
		&i.Description,
		&i.QueryType,
		&i.Source,
		&i.Params,
		&i.Headers,
		&i.Auth,
		&i.TimeoutMs,
		&i.MockData,
		&i.MockDataEnabled,
		&i.Active,
		&i.DeletedAt,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
