// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    workspace_id,
    identity,
    display_name,
    code,
    description,
    folder_id,
    configuration
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, workspace_id, identity, display_name, code, description, folder_id, configuration, created_at, updated_at
`

type CreateTenantParams struct {
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	Identity      string      `json:"identity"`
	DisplayName   string      `json:"display_name"`
	Code          string      `json:"code"`
	Description   pgtype.Text `json:"description"`
	FolderID      pgtype.UUID `json:"folder_id"`
	Configuration []byte      `json:"configuration"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.WorkspaceID,
		arg.Identity,
		arg.DisplayName,
		arg.Code,
		arg.Description,
		arg.FolderID,
		arg.Configuration,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Identity,
		&i.DisplayName,
		&i.Code,
		&i.Description,
		&i.FolderID,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByIdentity = `-- name: GetTenantByIdentity :one
SELECT id, workspace_id, identity, display_name, code, description, folder_id, configuration, created_at, updated_at
FROM tenants
WHERE workspace_id = $1
  AND identity = $2
`

type GetTenantByIdentityParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Identity    string    `json:"identity"`
}

func (q *Queries) GetTenantByIdentity(ctx context.Context, arg GetTenantByIdentityParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByIdentity, arg.WorkspaceID, arg.Identity)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Identity,
		&i.DisplayName,
		&i.Code,
		&i.Description,
		&i.FolderID,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantFolderByID = `-- name: GetTenantFolderByID :one
SELECT id
FROM folders
WHERE id = $1
  AND workspace_id = $2
  AND entity_type = 'tenants'
  AND deleted_at IS NULL
`

type GetTenantFolderByIDParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetTenantFolderByID(ctx context.Context, arg GetTenantFolderByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantFolderByID, arg.ID, arg.WorkspaceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTenantRootFolder = `-- name: GetTenantRootFolder :one
SELECT id
FROM folders
WHERE workspace_id = $1
  AND project_id IS NULL
  AND entity_type = 'tenants'
  AND identity = 'root-tenants'
  AND is_root = TRUE
  AND deleted_at IS NULL
`

func (q *Queries) GetTenantRootFolder(ctx context.Context, workspaceID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantRootFolder, workspaceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const hardDeleteTenant = `-- name: HardDeleteTenant :execrows
DELETE FROM tenants
WHERE workspace_id = $1
  AND identity = $2
`

type HardDeleteTenantParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Identity    string    `json:"identity"`
}

func (q *Queries) HardDeleteTenant(ctx context.Context, arg HardDeleteTenantParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteTenant, arg.WorkspaceID, arg.Identity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, workspace_id, identity, display_name, code, description, folder_id, configuration, created_at, updated_at
FROM tenants
WHERE workspace_id = $1
  AND (
    $2::uuid IS NULL
    OR folder_id = $2
  )
ORDER BY created_at DESC
`

type ListTenantsParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.WorkspaceID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Identity,
			&i.DisplayName,
			&i.Code,
			&i.Description,
			&i.FolderID,
			&i.Configuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    display_name = $1,
    code = $2,
    description = $3,
    folder_id = $4,
    configuration = $5,
    updated_at = NOW()
WHERE workspace_id = $6
  AND identity = $7
RETURNING id, workspace_id, identity, display_name, code, description, folder_id, configuration, created_at, updated_at
`

type UpdateTenantParams struct {
	DisplayName   string      `json:"display_name"`
	Code          string      `json:"code"`
	Description   pgtype.Text `json:"description"`
	FolderID      pgtype.UUID `json:"folder_id"`
	Configuration []byte      `json:"configuration"`
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	Identity      string      `json:"identity"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.DisplayName,
		arg.Code,
		arg.Description,
		arg.FolderID,
		arg.Configuration,
		arg.WorkspaceID,
		arg.Identity,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Identity,
		&i.DisplayName,
		&i.Code,
		&i.Description,
		&i.FolderID,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
