// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const upsertCurrentUser = `-- name: UpsertCurrentUser :one
INSERT INTO service_users (provider_id, subject, issuer, username, display_name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider_id, issuer, subject) DO UPDATE SET
  issuer = EXCLUDED.issuer,
  username = CASE WHEN EXCLUDED.username <> '' THEN EXCLUDED.username ELSE service_users.username END,
  display_name = CASE WHEN EXCLUDED.display_name <> '' THEN EXCLUDED.display_name ELSE service_users.display_name END,
  updated_at = NOW(),
  last_seen_at = NOW()
RETURNING id, provider_id, subject, issuer, username, display_name, active, created_at, updated_at, last_seen_at
`

type UpsertCurrentUserParams struct {
	ProviderID  string `json:"provider_id"`
	Subject     string `json:"subject"`
	Issuer      string `json:"issuer"`
	Username    string `json:"username"`
	DisplayName string `json:"display_name"`
}

type UpsertCurrentUserRow struct {
	ID          uuid.UUID `json:"id"`
	ProviderID  string    `json:"provider_id"`
	Subject     string    `json:"subject"`
	Issuer      string    `json:"issuer"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	Active      bool      `json:"active"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}

func (q *Queries) UpsertCurrentUser(ctx context.Context, arg UpsertCurrentUserParams) (UpsertCurrentUserRow, error) {
	row := q.db.QueryRow(ctx, upsertCurrentUser,
		arg.ProviderID,
		arg.Subject,
		arg.Issuer,
		arg.Username,
		arg.DisplayName,
	)
	var i UpsertCurrentUserRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Subject,
		&i.Issuer,
		&i.Username,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
