// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const upsertServiceUserFromIdentity = `-- name: UpsertServiceUserFromIdentity :one
INSERT INTO service_users (
  id,
  auth_user_id,
  username,
  display_name,
  role,
  created_at,
  updated_at
)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (auth_user_id) DO UPDATE
SET
  username = CASE
    WHEN EXCLUDED.username <> '' THEN EXCLUDED.username
    ELSE service_users.username
  END,
  display_name = CASE
    WHEN EXCLUDED.display_name <> '' THEN EXCLUDED.display_name
    ELSE service_users.display_name
  END,
  role = CASE
    WHEN EXCLUDED.role <> '' THEN EXCLUDED.role
    ELSE service_users.role
  END,
  updated_at = NOW()
RETURNING id, auth_user_id, username, display_name, role, created_at, updated_at
`

type UpsertServiceUserFromIdentityParams struct {
	ID          uuid.UUID `json:"id"`
	AuthUserID  string    `json:"auth_user_id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	Role        string    `json:"role"`
}

func (q *Queries) UpsertServiceUserFromIdentity(ctx context.Context, arg UpsertServiceUserFromIdentityParams) (ServiceUser, error) {
	row := q.db.QueryRow(ctx, upsertServiceUserFromIdentity,
		arg.ID,
		arg.AuthUserID,
		arg.Username,
		arg.DisplayName,
		arg.Role,
	)
	var i ServiceUser
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
