// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    identity,
    display_name,
    configuration
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, identity, display_name, configuration, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Identity      string `json:"identity"`
	DisplayName   string `json:"display_name"`
	Configuration []byte `json:"configuration"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.Identity, arg.DisplayName, arg.Configuration)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByIdentity = `-- name: GetWorkspaceByIdentity :one
SELECT id, identity, display_name, configuration, created_at, updated_at
FROM workspaces
WHERE identity = $1
`

func (q *Queries) GetWorkspaceByIdentity(ctx context.Context, identity string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByIdentity, identity)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, identity, display_name, configuration, created_at, updated_at
FROM workspaces
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Identity,
			&i.DisplayName,
			&i.Configuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET
    display_name = $1,
    configuration = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, identity, display_name, configuration, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	DisplayName   string    `json:"display_name"`
	Configuration []byte    `json:"configuration"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.DisplayName, arg.Configuration, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Identity,
		&i.DisplayName,
		&i.Configuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
