app:
  env: local
  name: service_backend
  version: 0.1.0
  public_url: http://localhost:8080

http:
  port: "8080"
  cors_allowed_origins: http://localhost:5173

logger:
  level: debug

metrics:
  enabled: false

postgres:
  host: hacofelasog.beget.app
  port: 5432

  user: endge-backend
  password: "U5aDnPNB9b%e"   # см. примечание ниже

  database: endge_backend
  schema: public

  sslmode: require

  conn_timeout: 5

  max_conn: 100
  min_conn: 1

  max_conn_lifetime: 25m
  max_conn_idle_time: 5m

  migrations_enabled: true

auth:
  enabled: false
  service_url: ""
  issuer: ""
  allowed_audiences: ""
  jwks_path: /.well-known/jwks.json
  jwks_cache_ttl: 5m
  timeout: 5s

telemetry:
  enabled: false
  otlp_endpoint: ""
  otlp_insecure: true

redpanda:
  enabled: false
  brokers: ""
  client_id: service_backend
  dial_timeout: 5s
  read_batch_timeout: 2s
  write_timeout: 10s
